- name: Make sure everything is up to date
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true

- name: Check if a reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  ansible.builtin.reboot:
  when: reboot_required_file.stat.exists

- name: Install packages
  ansible.builtin.apt:
    pkg:
      - git
      - gnuradio
      - xterm

- name: Pull the latest code from the repository
  become: false
  ansible.builtin.git:
    repo: 'https://github.com/marnicbar/sdr_demo.git'
    dest: /home/{{ ansible_user }}/sdr_demo
    version: main

- name: Ensure user systemd directory exists
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/.config/systemd/user
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

# Only needed for the receiver but it is included in both so the transmitter can
# be easily switched to the receiver role if needed without requiring another setup run
- name: Set the default ALSA audio device to card 1
  ansible.builtin.copy:
    dest: /etc/asound.conf
    content: |
      defaults.pcm.card 1
      defaults.ctl.card 1
    owner: root
    group: root
    mode: '0644'
  notify: Reboot device

- name: Disable popup window but keep automount (PCManFM default profile)
  become: true
  become_user: "{{ ansible_user }}"
  community.general.ini_file:
    path: /home/{{ ansible_user }}/.config/pcmanfm/default/pcmanfm.conf
    section: volume
    option: autorun
    value: "0"
    create: true
    no_extra_spaces: true
    mode: '0644'
  notify: Reboot device
