---
- name: Setup a Raspberry Pi as the receiver node
  hosts: receiver_pi
  become: true

  tasks:
    - name: Include common Raspberry Pi setup tasks
      ansible.builtin.import_tasks:
        file: common_rpi_setup.yml

    - name: Set the default ALSA audio device to card 1
      ansible.builtin.copy:
        dest: /etc/asound.conf
        content: |
          defaults.pcm.card 1
          defaults.ctl.card 1
        owner: root
        group: root
        mode: '0644'

    - name: Configure the system to run the receiver script on boot
      ansible.builtin.copy:
        dest: /etc/systemd/system/receiver.service
        content: |
          [Unit]
          Description=SDR Receiver Service
          After=network.target graphical.target
          Wants=network.target graphical.target

          [Service]
          ExecStart=/home/{{ ansible_user }}/sdr_demo/run_receiver.sh
          WorkingDirectory=/home/{{ ansible_user }}/sdr_demo
          Restart=always
          User={{ ansible_user }}

          [Install]
          WantedBy=graphical.target
        owner: root
        group: root
        mode: '0644'

    - name: Reload systemd to recognize new service
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Enable and start the receiver systemd service
      ansible.builtin.systemd:
        name: receiver.service
        enabled: true
        state: started
