---
- name: Setup a Raspberry Pi as the transmitter node
  hosts: transmitter_pi
  become: true

  tasks:
    - name: Include common Raspberry Pi setup tasks
      ansible.builtin.import_tasks:
        file: common_rpi_setup.yml

    - name: Set the default ALSA audio device to card 1
      ansible.builtin.copy:
        dest: /etc/asound.conf
        content: |
          defaults.pcm.card 1
          defaults.ctl.card 1
        owner: root
        group: root
        mode: '0644'

    - name: Configure the system to run the transmitter script on boot
      ansible.builtin.copy:
        dest: /home/{{ ansible_user }}/.config/systemd/user/transmitter.service
        content: |
          [Unit]
          Description=SDR Transmitter GUI Service
          After=graphical-session.target network.target
          Wants=graphical-session.target network.target

          [Service]
          ExecStart=/home/{{ ansible_user }}/sdr_demo/run_transmitter.sh
          WorkingDirectory=/home/{{ ansible_user }}/sdr_demo
          Restart=always
          Environment=DISPLAY=:0
          Environment=XAUTHORITY=/home/{{ ansible_user }}/.Xauthority
          StandardOutput=append:/home/{{ ansible_user }}/sdr_demo/transmitter.log
          StandardError=append:/home/{{ ansible_user }}/sdr_demo/transmitter.log

          [Install]
          WantedBy=default.target
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'

    - name: Start user systemd service 'transmitter'
      ansible.builtin.systemd:
        name: transmitter.service
        state: started
        scope: user
        enabled: true
      become: true
      become_user: "{{ ansible_user }}"
